### ISSUE TITLE
[Feature Request]: Auto-play feature?

### ISSUE THREAD

**Issue by dalisoft** [mifi/reactive-video#2]
Hi @mifi 

Thank you for hard work, can you please give me point to get auto-play working with pause controlling?

**Comment by mifi** [comment]
it's abit tricky because the ffmpeg video rendering or html5 video seeking is usually not as fast as realtime, so videos would stutter. But it will work for any non-video layers, so I will definitely add that feature.

**Comment by dalisoft** [comment]
Yes, i also think is there any way to use GPU rendering (in `editly`) and if possible, i'd like to try. Thank you for reply
