### ISSUE TITLE
Cloud - Puppeteer args

### ISSUE THREAD

**Issue by IvanDhalluin** [mifi/reactive-video#7]
Hi,
I am using your lib to run with GCP Cloud Run. It works great!

My only concern is that I needed to disable Puppeteer sandbox : `'--no-sandbox', '--disable-setuid-sandbox'` ([Setting Up Chrome Linux Sandbox](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox))

Maybe you can allow access to Puppeteer args in Editor config?

**Comment by mifi** [comment]
Sure! maybe an option extraPuppeteerArgs to `edit()`. pr welcome btw!
